services:
  proxy:
    container_name: proxyapp
    image: nginx
    volumes:
      - ./.docker/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  rtmp:
    container_name: rtmpstreaming
    build:
      context: .
      dockerfile: ./.docker/rtmp/dev/Dockerfile
    volumes:
      - ./.docker/rtmp/dev/tmp:/tmp
    ports:
      - 1935:1935

  nuxt:
    container_name: appnuxt
    build:
      context: .
      dockerfile: ./.docker/nuxt/dev/Dockerfile
    volumes:
      - ./app:/app
    env_file:
      - .env

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    ports:
      - 27017:27017
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${DATABASE_TYPE}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?authSource=admin
      ME_CONFIG_BASICAUTH: false